<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <Company>Skyline Communications</Company>
    <Copyright>© Skyline Communications</Copyright>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <LangVersion>7.3</LangVersion>
    <RootNamespace>QAction_1992</RootNamespace>
    <AssemblyName>QAction_1992</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\QAction_Helper\QAction_Helper.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Skyline.DataMiner.Dev.Protocol" Version="10.2.0.25" />
    <PackageReference Include="Skyline.DataMiner.Utils.SNMP" Version="1.0.0.2" />
    <PackageReference Include="Skyline.DataMiner.Utils.SecureCoding.Analyzers" Version="2.2.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Skyline.DataMiner.Utils.Protocol.Extension" Version="1.0.0.4" />
  </ItemGroup>
  <ProjectExtensions>
    <VisualStudio><UserProperties DisLinkedXmlFile="..\protocol.xml" DisLinkId="1992" DisProjectType="qactionProject" /></VisualStudio>
  </ProjectExtensions>
</Project>